name: alumni_portal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  http_parser: ^4.0.2
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0  # upgraded
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo1.png
    

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo1.png"
  adaptive_icon_foreground: "assets/logo1.png"

flutter_native_splash:
  color: "#ffffff"  # background color
  image: "assets/logo1.png" # use your existing logo
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true
